version: '3.0'

services:
  postgres:
    image: postgres
    container_name: course-api-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: course
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data